name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  notion-token:
    description: 'Notion token'
    required: true
  property:
    description: 'Notion page property'
    required: true
  value:
    description: 'Notion page value'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node20'
  main: 'dist/index.js'
