name: 'Notion Connect'
description: 'Greet someone and record the time'
inputs:
  token:
    description: 'GitHub token'
    required: true
  notion-token:
    description: 'Notion token'
    required: true
  property:
    description: 'Notion page property'
    required: true
  property-type:
    description: 'Notion page property type'
    required: true
  value:
    description: 'Notion page value'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'activity'
  color: 'purple'
